version: '3.8'

services:
  mongodb:
    image: mongo:4.4.21
    container_name: mongodb
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=mei23907
      - MONGODB_INITDB_ROOT_PASSWORD=mei23907
    ports:
      - 27017:27017
  mosquitto:
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    container_name: mosquitto
    volumes:
      - type: bind
        source: ./mosquitto/config/
        target: /mosquitto/config/
      - type: bind
        source: ./mosquitto/log/
        target: /mosquitto/log/
      - type: volume
        source: data
        target: /mosquitto/data/
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
  node-red:
    image: nodered/node-red
    container_name: mynodered
    volumes:
      - node_red_data:/data
    ports:
      - 1880:1880
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - portainer_data:/data - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    ports:
      - 8000:8000
      - 9443:9443

volumes:
  portainer_data:
  mosquitto_data:
  mosquitto_log:
  mosquitto:
  mongo-data:
  node_red_data:
  data:
    name: "mqtt-broker-data"